package:
  name: gneiss
  version: 0.1.0

source:
  git_url: https://github.com/biocore/gneiss.git


requirements:
  build:
    - python
    - pandas
    - scipy
    - numpy
    - matplotlib
    - scikit-bio ==0.5.1
    - pyqt ==4.11.4
  run:
    - python
    - pandas
    - scipy
    - numpy
    - matplotlib
    - scikit-bio ==0.5.1
    - pyqt ==4.11.4

test:
  # Python imports
  imports:
    - gneiss

about:
  home: https://github.com/biocore/gneiss
  license: GPLv3 License
  summary: Compositional Analysis and Visualization toolkit
