package:
  name: gneiss
  version: 0.3.2

source:
  git_url: https://github.com/biocore/gneiss.git
  git_rev: v0.3.2

build:
  number: 5

requirements:
  build:
    - setuptools
    - python
    - scikit-bio >=0.5.1
    - pandas
    - scipy
    - numpy >=1.11
    - matplotlib
    - bokeh
    - seaborn
    - h5py
    - statsmodels >=0.8.0
    - biom-format
    - qiime2 ==2017.2.0
    - q2cli ==2017.2.0
    - q2-types ==2017.2.0
    - q2-feature-table ==2017.2.0
    - q2-composition ==2017.2.0
    - pip
  run:
    - setuptools
    - python
    - scikit-bio >=0.5.1
    - pandas
    - scipy
    - numpy >=1.11
    - matplotlib
    - bokeh
    - seaborn
    - h5py
    - statsmodels >=0.8.0
    - biom-format
    - qiime2 ==2017.2.0
    - q2cli ==2017.2.0
    - q2-types ==2017.2.0
    - q2-feature-table ==2017.2.0
    - q2-composition ==2017.2.0
    - pip


test:
  # Python imports
  imports:
    - gneiss

about:
  home: https://github.com/biocore/gneiss
  license: BSD License
  summary: Compositional Analysis and Visualization toolkit
