package:
  name: gneiss
<<<<<<< HEAD
  version: 0.3.0

source:
  git_url: https://github.com/biocore/gneiss.git
  git_rev: 0.3.0

build:
  number: 1

requirements:
  build:
    - python ==3.5
    - scikit-bio
=======
  version: 0.3.2

source:
  git_url: https://github.com/biocore/gneiss.git
  git_rev: v0.3.2

build:
  number: 5

requirements:
  build:
    - setuptools
    - python
    - scikit-bio >=0.5.1
>>>>>>> 18820d530f0cbd5f741d77f0b92e31bdef4e900a
    - pandas
    - scipy
    - numpy >=1.11
    - matplotlib
    - bokeh
    - seaborn
<<<<<<< HEAD
=======
    - h5py
    - statsmodels >=0.8.0
    - biom-format
>>>>>>> 18820d530f0cbd5f741d77f0b92e31bdef4e900a
    - qiime2 ==2017.2.0
    - q2cli ==2017.2.0
    - q2-types ==2017.2.0
    - q2-feature-table ==2017.2.0
    - q2-composition ==2017.2.0
<<<<<<< HEAD
  run:
    - python ==3.5
    - scikit-bio
=======
    - pip
  run:
    - setuptools
    - python
    - scikit-bio >=0.5.1
>>>>>>> 18820d530f0cbd5f741d77f0b92e31bdef4e900a
    - pandas
    - scipy
    - numpy >=1.11
    - matplotlib
    - bokeh
    - seaborn
<<<<<<< HEAD
=======
    - h5py
    - statsmodels >=0.8.0
    - biom-format
>>>>>>> 18820d530f0cbd5f741d77f0b92e31bdef4e900a
    - qiime2 ==2017.2.0
    - q2cli ==2017.2.0
    - q2-types ==2017.2.0
    - q2-feature-table ==2017.2.0
    - q2-composition ==2017.2.0
<<<<<<< HEAD
=======
    - pip
>>>>>>> 18820d530f0cbd5f741d77f0b92e31bdef4e900a


test:
  # Python imports
  imports:
    - gneiss

about:
  home: https://github.com/biocore/gneiss
  license: BSD License
  summary: Compositional Analysis and Visualization toolkit
