package:
  name: gneiss
  version: 0.3.0

source:
  git_url: https://github.com/biocore/gneiss.git
  git_rev: 0.3.0

build:
  number: 1

requirements:
  build:
    - python ==3.5
    - scikit-bio
    - pandas
    - scipy
    - numpy
    - matplotlib
    - bokeh
    - seaborn
    - qiime2 ==2017.2.0
    - q2cli ==2017.2.0
    - q2-types ==2017.2.0
    - q2-feature-table ==2017.2.0
    - q2-composition ==2017.2.0
  run:
    - python ==3.5
    - scikit-bio
    - pandas
    - scipy
    - numpy
    - matplotlib
    - bokeh
    - seaborn
    - qiime2 ==2017.2.0
    - q2cli ==2017.2.0
    - q2-types ==2017.2.0
    - q2-feature-table ==2017.2.0
    - q2-composition ==2017.2.0


test:
  # Python imports
  imports:
    - gneiss

about:
  home: https://github.com/biocore/gneiss
  license: BSD License
  summary: Compositional Analysis and Visualization toolkit
