package:
  name: gneiss
  version: 0.4.0

source:
  git_url: https://github.com/biocore/gneiss.git
  git_rev: v0.4.0

build:
  number: 6

requirements:
  build:
    - setuptools
    - python 3.5*
  run:
    - setuptools
    - python 3.5*
    - pandas
    - scipy
    - numpy >=1.11
    - matplotlib
    - bokeh
    - seaborn
    - h5py
    - statsmodels 0.8.0
    - biom-format
    - qiime2 2017.6.0
    - q2cli 2017.6.0
    - q2-types 2017.6.0
    - q2-composition 2017.6.0
    - pip


test:
  # Python imports
  imports:
    - gneiss
    - qiime2.plugins.gneiss

about:
  home: https://github.com/biocore/gneiss
  license: BSD License
  summary: Compositional Analysis and Visualization toolkit
