os:
  - linux
  - osx
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
env:
  matrix:
    # CONDA_PY and CONDA_NPY are the env variable of python version
    # and numpy version used by "conda build"
    # to build the packages.
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    - secure: O6uWI000uv3U7IOKo2leTTomzeO+sb/uzeV0JYRfcAUyo6nfp3T2WxcOzC/1NZzVkRahNPsMW751EJF2DJXK8+lgyMlbaMrgZegvB2dkDKfEou+hdS20Ty6+RxyOB9ZLUQ7sYT828Ajc/w/kWVD80tW5hA3yN76gZjWgERQbiebeFrwwqWPV8VREkwo/ASfgq2IlAtvHBE8wow8E/YeuzKNIbAcSlrWWifYtyOqdfkuLXn2hZfVQJxbOqPe1H0ZUGKblJFoPCQrJq3fqZV7CnteWbm8zctu7szsUpKj6mchQuPrb0dwiy8PInITtr+DDuZ63XdSu0xxYOdjYQxzuDlMCvgncB3mFjfs3Sd7u1zA7ZQ3Sk2zMz05WaN7HWgStsGnJ0QhRmsSjrAtqH19cPTH0qH5dwYh/HL+RvvQR9SLZoW+47nS7ukT8eABltGFrCumZA2bHrtrS4sQL20xp52cM4qVn5giPNNr1Ri7jzLcvL4PqcMM8jqzWO5FxUEmMn656JkGTU5NPMcopu1b6/pfvfD0dylREzEKKdaARVamki5zBA2zlGgF8g+PTPQyAw14B8EeNIS4Q7FMycYWm6n7Kv0sUT/uft5gvv1Rps3KTO90C58gCev+wyszBINiGrtrDNWW5xzosrSEoX+hmlICL+Wnjy1oVT84k8rLEmDE=
install:
  - source ci/travis/install.sh
script:
  - python ci/main.py recipes biocore
