package:
  name: deblur
  version: "1.0.0"

source:
  git_url: https://github.com/biocore/deblur.git
  git_rev: 1.0.0

build:
  number: 2

requirements:
  build:
    - python
    - biom-format
    - setuptools
    - scikit-bio >=0.5.0
    - vsearch ==2.0.3
    - mafft ==7.221
    - sortmerna ==2.0
    - h5py
    - click

  run:
    - python
    - biom-format
    - setuptools
    - scikit-bio >=0.5.0
    - vsearch ==2.0.3
    - mafft ==7.221
    - sortmerna ==2.0
    - h5py
    - click

test:
  imports:
    - deblur
  commands:
    - deblur --help
about:
  home: https://github.com/biocore/deblur
  license: BSD license
