package:
  name: deblur
  version: "1.0.1"

source:
  git_url: https://github.com/biocore/deblur.git
  git_rev: 1.0.1

build:
  number: 1
  
requirements:
  build:
    - setuptools
    - python
    - scikit-bio
    - vsearch ==2.0.3
    - mafft ==7.221
    - sortmerna ==2.0
    - biom-format
    - h5py
    - click
    - pip

  run:
    - setuptools
    - python
    - scikit-bio
    - vsearch ==2.0.3
    - mafft ==7.221
    - sortmerna ==2.0
    - biom-format
    - h5py
    - click
    - pip

test:
  imports:
    - deblur

about:
  home: https://github.com/biocore/deblur
  license: BSD license
