package:
  name: memsat-svm
  version: "1.3"

source:
  url: http://bioinfadmin.cs.ucl.ac.uk/downloads/memsat-svm/memsat-svm1.3.tar.gz
  md5: 245896ff433d361fdd969b72be440359

build:
  number: 0

test:
  files:
    - swissprot-rat.fasta.gz
    - test_input.fasta
    - test_input.mtx
    - test_result.out
  requires:
    - blast-legacy ==2.2.22
  commands:
    - gunzip -f swissprot-rat.fasta.gz
    - formatdb -p T -i swissprot-rat.fasta -n swissprot-rat.fasta
    - mkdir -p runFasta/output runFasta/input
    - run_memsat-svm.pl -p 1 -mtx 0 -j runFasta/output/ -e 0 -i runFasta/input/ -d swissprot-rat.fasta test_input.fasta
    - diff runFasta/output/test_input_SVM_ALL.out test_result.out
    - mkdir -p runMtx/output runMtx/input
    - run_memsat-svm.pl -p 1 -mtx 1 -j runMtx/output/ -e 0 -i runMtx/input/ -d swissprot-rat.fasta test_input.mtx
    - diff runMtx/output/test_input_SVM_ALL.out test_result.out

requirements:
  run:
    - blast-legacy ==2.2.22

about:
  summary: SVM Transmembrane protein structure prediction
  home: http://bioinf.cs.ucl.ac.uk/software_downloads/
